"""Generate docs/topics.js from topics.json plus the real Python sources.

The website never stores its own copy of the code - it is embedded here at
build time, straight from the .py files. Edit a script, re-run this, and the
site is back in sync.

Run:  python build_site.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).parent
REPO = "https://github.com/iyu210-tech/Capstone_Repository"


def main():
    topics = json.loads((ROOT / "topics.json").read_text(encoding="utf-8"))

    for t in topics:
        folder = ROOT / t["folder"]
        script = folder / t["script"]
        if not script.exists():
            raise SystemExit(f"missing script: {script}")

        t["source"] = script.read_text(encoding="utf-8")
        t["script_url"] = f"{t['folder']}/{t['script']}"
        t["notebook_url"] = f"{REPO}/blob/main/{t['folder']}/{t['notebook']}"
        t["colab_url"] = (
            f"https://colab.research.google.com/github/iyu210-tech/"
            f"Capstone_Repository/blob/main/{t['folder']}/{t['notebook']}"
        )

    out = ROOT / "docs" / "topics.js"
    out.parent.mkdir(exist_ok=True)
    payload = json.dumps(topics, indent=2, ensure_ascii=False)
    out.write_text(
        "// GENERATED by build_site.py - do not edit by hand.\n"
        f"window.TOPICS = {payload};\n",
        encoding="utf-8",
    )
    print(f"wrote {out} ({len(topics)} topics, {out.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
