"""Generate the website's derived files from topics.json plus the real sources.

The website never stores its own copy of the code - it is embedded here at
build time, straight from the .py files. Edit a script, re-run this, and the
site is back in sync.

What it writes, all under docs/:

  topics.js          every topic, with its Python source embedded
  t/<id>/index.html  a real page per topic, so a link can be crawled and shared
  og/<id>.png        the link-preview image for each topic, plus og/home.png
  sitemap.xml        every page, for search engines
  robots.txt         points crawlers at the sitemap
  index.html         only its canonical and preview URLs, which follow SITE_URL

Everything here is stdlib only. Vercel and Render both run this with no pip
install, and it has to stay that way - the topic scripts' matplotlib/scipy
dependencies are for running the topics, not for building the site.

Run:  python build_site.py
      SITE_URL=https://example.vercel.app/ python build_site.py
      python build_site.py --root path/to/another/checkout
"""

import argparse
import html
import json
import math
import os
import re
import shutil
import struct
import sys
import unicodedata
import zlib
from pathlib import Path

ROOT = Path(__file__).parent
REPO = "https://github.com/iyu210-tech/Capstone_Repository"

# The README treats GitHub Pages as the main address, so that is what every
# canonical URL points at unless the host says otherwise. Vercel and Render set
# SITE_URL to their own address if they should be indexed as themselves; left
# unset, they declare themselves copies of this one, which is also correct.
DEFAULT_SITE_URL = "https://iyu210-tech.github.io/Capstone_Repository/"

SITE_NAME = "IB HL Visualisations"
MARKER = "GENERATED by build_site.py - do not edit"

# (field, type) - every topic needs all of these. The site renders each one,
# so a missing field is a broken page rather than a blank space.
REQUIRED = [
    ("id", str), ("title", str), ("subject", str), ("syllabus", str),
    ("folder", str), ("script", str), ("notebook", str), ("tags", list),
    ("hard_bit", str), ("shows", str),
]

# The id is now a URL segment (t/<id>/) and a folder name, so it has to be
# something that survives both without escaping.
ID_PATTERN = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


class BuildError(Exception):
    """Something in topics.json or the tree would ship a broken site."""


# --------------------------------------------------------------- settings
def site_url(value=None):
    """SITE_URL, normalised to end in exactly one slash.

    Everything else joins paths onto it ("t/<id>/", "og/home.png"), so the
    slash is what keeps "…/Capstone_Repository" from swallowing the next bit.
    """
    url = (value if value is not None else os.environ.get("SITE_URL", "")).strip()
    url = url or DEFAULT_SITE_URL
    if not re.match(r"^https?://[^/\s]+", url):
        raise BuildError(f"SITE_URL must be an absolute http(s) URL, got {url!r}")
    return url.rstrip("/") + "/"


# ------------------------------------------------------------- validation
def demo_builders(root):
    """The demo names docs/demos.js can mount, read from its BUILDERS object.

    A regex rather than a JS parser: the registry is one flat object literal
    by design, and this only has to notice a "demo" value with no builder -
    which otherwise fails silently as a topic page with no animation.
    """
    path = root / "docs" / "demos.js"
    if not path.exists():
        return None
    m = re.search(r"\bBUILDERS\s*=\s*\{(.*?)\}", path.read_text(encoding="utf-8"), re.S)
    if not m:
        return None
    return set(re.findall(r"""["']?([A-Za-z_$][\w$]*)["']?\s*:""", m.group(1)))


def _is_str_list(v):
    return isinstance(v, list) and all(isinstance(x, str) and x.strip() for x in v)


def _is_record_list(v, keys):
    return isinstance(v, list) and all(
        isinstance(x, dict) and all(isinstance(x.get(k), str) and x[k].strip() for k in keys)
        for x in v
    )


# Content fields that are optional, and their shape when present. Anything not
# listed here is passed through to topics.js untouched, so a new field does not
# need a build change before it can be tried out.
OPTIONAL = {
    "demo": (lambda v: isinstance(v, str) and v.strip(), "a non-empty string"),
    "try_changing": (_is_str_list, "a list of non-empty strings"),
    "equations": (lambda v: _is_record_list(v, ("tex", "caption")),
                  'a list of {"tex": str, "caption": str}'),
    "questions": (lambda v: _is_record_list(v, ("q", "a")),
                  'a list of {"q": str, "a": str}'),
}


def validate(topics, root):
    """Raise BuildError listing every problem at once, or return None.

    All of them together, not the first: fixing one, rebuilding, and finding
    the next is the slow way to learn you mistyped three folder names.
    """
    problems = []
    if not isinstance(topics, list):
        raise BuildError("topics.json must be a JSON list of topic objects")

    builders = demo_builders(root)
    seen = {}

    for i, t in enumerate(topics):
        if not isinstance(t, dict):
            problems.append(f"entry {i}: must be an object, got {type(t).__name__}")
            continue
        label = t["id"] if isinstance(t.get("id"), str) and t["id"] else f"entry {i}"

        broken = False
        for field, kind in REQUIRED:
            if field not in t:
                problems.append(f'{label}: missing required field "{field}"')
                broken = True
            elif not isinstance(t[field], kind) or (kind is str and not t[field].strip()):
                want = "a non-empty string" if kind is str else "a list"
                problems.append(f'{label}: "{field}" must be {want}')
                broken = True
        if isinstance(t.get("tags"), list) and not _is_str_list(t["tags"]):
            problems.append(f'{label}: "tags" must be a list of non-empty strings')

        for field, (ok, want) in OPTIONAL.items():
            if field in t and not ok(t[field]):
                problems.append(f'{label}: "{field}" must be {want}')

        tid = t.get("id")
        if isinstance(tid, str) and tid:
            if not ID_PATTERN.match(tid):
                problems.append(f'{label}: id must be lowercase words joined by '
                                f'hyphens (it becomes the URL t/{tid}/)')
            if tid in seen:
                problems.append(f'{label}: duplicate id (entries {seen[tid]} and {i})')
            else:
                seen[tid] = i

        if broken:
            continue   # the path checks below need the fields that are missing

        folder = root / t["folder"]
        if not folder.is_dir():
            problems.append(f'{label}: folder "{t["folder"]}" does not exist')
        else:
            for field in ("script", "notebook"):
                if not (folder / t[field]).is_file():
                    problems.append(f'{label}: {field} "{t["folder"]}/{t[field]}" does not exist')
        if Path(t["folder"]).name != t["id"]:
            problems.append(f'{label}: folder "{t["folder"]}" must end in the id '
                            f'("{t["id"]}"), so the URL and the folder agree')

        demo = t.get("demo")
        if isinstance(demo, str) and demo.strip():
            if builders is None:
                problems.append(f'{label}: has demo "{demo}" but no BUILDERS registry '
                                f'was found in docs/demos.js')
            elif demo not in builders:
                known = ", ".join(sorted(builders)) or "none"
                problems.append(f'{label}: demo "{demo}" has no builder in docs/demos.js '
                                f'(known: {known})')

    if problems:
        n = len(problems)
        raise BuildError(f"topics.json has {n} problem{'s' if n != 1 else ''}:\n"
                         + "\n".join("  - " + p for p in problems))


# ------------------------------------------------------------------- html
def esc(s):
    return html.escape(s, quote=True)


def summary(text, limit=200):
    """One line of at most `limit` characters, cut on a word boundary."""
    text = " ".join(text.split())
    if len(text) <= limit:
        return text
    return text[:limit - 1].rsplit(" ", 1)[0].rstrip(",;:- ") + "…"


def _sub_once(pattern, repl, doc, what):
    """re.subn that insists on exactly one match.

    The template is docs/index.html, which other people edit. If a tag this
    fills in has gone, say so - silently shipping every topic page with the
    home page's canonical URL is exactly the bug this build exists to fix.
    """
    out, n = re.subn(pattern, lambda m: repl(m), doc, count=1, flags=re.S)
    if n != 1:
        raise BuildError(f"docs/index.html: could not find {what}; build_site.py "
                         f"fills it in, so the tag has to stay in the template")
    return out


def set_meta(doc, key, value):
    """Set <meta name|property="key" content="..."> to value."""
    pat = r'(<meta\s+(?:name|property)="' + re.escape(key) + r'"\s+content=")[^"]*(")'
    return _sub_once(pat, lambda m: m.group(1) + esc(value) + m.group(2), doc,
                     f'<meta … "{key}" content="…">')


def set_canonical(doc, url):
    pat = r'(<link\s+rel="canonical"\s+href=")[^"]*(")'
    return _sub_once(pat, lambda m: m.group(1) + esc(url) + m.group(2), doc,
                     '<link rel="canonical">')


def set_title(doc, title):
    return _sub_once(r"<title>.*?</title>", lambda m: f"<title>{esc(title)}</title>",
                     doc, "<title>")


def home_page(template, site):
    """docs/index.html with its host-specific URLs pointed at SITE_URL."""
    doc = set_canonical(template, site)
    doc = set_meta(doc, "og:url", site)
    doc = set_meta(doc, "og:image", site + "og/home.png")
    doc = set_meta(doc, "twitter:image", site + "og/home.png")
    return doc


def _relative_asset(m):
    """Prefix one src/href inside a <link> or <script> tag with ../../."""
    attr, url = m.group(1), m.group(2)
    if re.match(r"^(?:[a-zA-Z][a-zA-Z0-9+.-]*:|/|#|\?)", url) or not url:
        return m.group(0)   # absolute, root-relative, data: or a fragment
    return f'{attr}="../../{url}"'


def rebase_assets(doc):
    """Point the page's stylesheet and scripts two directories up.

    Relative paths rather than <base href>: a <base> would also re-aim every
    fragment link, so the skip link (#view) and the in-page #/ routes would
    jump to the home page. Root-relative "/style.css" is out too - on GitHub
    Pages the site lives under /Capstone_Repository/, not at /. "../../" from
    t/<id>/ is the site root on all three hosts without knowing where that is.

    Only <link> and <script> tags are touched. Relative URLs inside <template>
    markup are resolved against the address bar each time they are used, which
    the router changes, so they have to stay as fragments.
    """
    def fix_tag(m):
        return re.sub(r'\b(src|href)="([^"]*)"', _relative_asset, m.group(0))
    return re.sub(r"<(?:link|script)\b[^>]*>", fix_tag, doc)


# Relative paths only resolve from t/<id>/ with the trailing slash. Every host
# here redirects the bare directory to it (GitHub Pages, server.py, and Vercel
# via trailingSlash), but a proxy or a hand-typed link might not, and without
# it the page arrives unstyled with no scripts. This runs before any of them.
SLASH_GUARD = (
    '<script>/* ../../ only resolves from t/<id>/ - add the slash if a host did not. */\n'
    'if (!/\\/(index\\.html)?$/.test(location.pathname)) '
    'location.replace(location.pathname + "/" + location.search + location.hash);\n'
    '</script>\n'
)


def static_topic(t):
    """The topic as plain HTML, for crawlers and for anyone without JS.

    app.js replaces all of it with the interactive page on boot, so this only
    has to read well - it is the part of the page a search engine indexes.
    """
    folder_url = f"{REPO}/tree/main/{t['folder']}"
    parts = [
        '\n  <a class="back" href="../../">&#8592; All topics</a>',
        '  <article class="topic">',
        '    <header class="topic-head">',
        f'      <span class="pill">{esc(t["subject"])}</span>',
        f'      <h1 tabindex="-1">{esc(t["title"])}</h1>',
        f'      <p class="syllabus">{esc(t["syllabus"])} &middot; {esc(t["folder"])}</p>',
        '    </header>',
        '    <section class="two-up">',
        '      <div class="panel">',
        '        <h2>The hard bit</h2>',
        f'        <p>{esc(t["hard_bit"])}</p>',
        '      </div>',
        '      <div class="panel">',
        '        <h2>What this shows</h2>',
        f'        <p>{esc(t["shows"])}</p>',
        '      </div>',
        '    </section>',
    ]
    if t.get("try_changing"):
        parts += ['    <section class="panel">', '      <h2>Try changing</h2>', '      <ul>']
        parts += [f'        <li>{esc(x)}</li>' for x in t["try_changing"]]
        parts += ['      </ul>', '    </section>']
    if t.get("equations"):
        parts += ['    <section class="panel">', '      <h2>The maths</h2>']
        for e in t["equations"]:
            parts.append(f'      <p><code>{esc(e["tex"])}</code> &mdash; {esc(e["caption"])}</p>')
        parts.append('    </section>')
    if t.get("questions"):
        parts += ['    <section class="panel">', '      <h2>Check yourself</h2>']
        for q in t["questions"]:
            parts.append(f'      <details><summary>{esc(q["q"])}</summary>'
                         f'<p>{esc(q["a"])}</p></details>')
        parts.append('    </section>')
    parts += [
        '    <noscript>',
        '      <div class="noscript">',
        '        <p>The interactive version of this page needs JavaScript. The',
        f'           script, the notebook and a README are in <a href="{esc(folder_url)}">'
        f'{esc(t["folder"])}</a> on GitHub.</p>',
        '      </div>',
        '    </noscript>',
        '  </article>\n',
    ]
    return "\n".join(parts)


def topic_page(template, t, site):
    """docs/t/<id>/index.html, built from the home page as its template.

    Reading docs/index.html at build time, instead of keeping a second copy of
    the markup, means a header, footer or script change reaches every topic
    page on the next build without anyone remembering to copy it.
    """
    url = f"{site}t/{t['id']}/"
    image = f"{site}og/{t['id']}.png"
    desc = summary(t["shows"])

    doc = set_title(template, f"{t['title']} — {SITE_NAME}")
    doc = set_meta(doc, "description", desc)
    doc = set_canonical(doc, url)
    doc = set_meta(doc, "og:type", "article")
    doc = set_meta(doc, "og:title", t["title"])
    doc = set_meta(doc, "og:description", desc)
    doc = set_meta(doc, "og:url", url)
    doc = set_meta(doc, "og:image", image)
    doc = set_meta(doc, "twitter:title", t["title"])
    doc = set_meta(doc, "twitter:description", desc)
    doc = set_meta(doc, "twitter:image", image)
    doc = rebase_assets(doc)

    body = static_topic(t)
    doc = _sub_once(r'(<main id="view"[^>]*>).*?(</main>)',
                    lambda m: m.group(1) + body + m.group(2), doc, '<main id="view">')
    # After the doctype, never before it: anything ahead of <!doctype html>
    # drops the browser into quirks mode.
    doc = _sub_once(r"(<!doctype html>\n)", lambda m: m.group(1) + f"<!-- {MARKER}. "
                    "Built from docs/index.html and topics.json. -->\n", doc, "<!doctype html>")
    doc = _sub_once(r'(<meta charset="utf-8">\n)', lambda m: m.group(1) + SLASH_GUARD,
                    doc, '<meta charset="utf-8">')
    return doc


# ------------------------------------------------------- sitemap, robots
def sitemap(topics, site):
    urls = [site] + [f"{site}t/{t['id']}/" for t in topics]
    # No <lastmod>: the only honest source is git history, and a date taken
    # from file mtimes changes on every checkout, so CI would see the sitemap
    # as stale on every run.
    rows = "\n".join(f"  <url><loc>{html.escape(u)}</loc></url>" for u in urls)
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            f"<!-- {MARKER}. -->\n"
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            f"{rows}\n</urlset>\n")


def robots(site):
    # Crawlers only read robots.txt at the root of a host, so on GitHub Pages
    # (served under /Capstone_Repository/) this file is ignored - submit the
    # sitemap in Search Console there instead. On Vercel and Render it is the
    # root, and this is how the sitemap is found.
    return (f"# {MARKER}.\n"
            "User-agent: *\n"
            "Allow: /\n\n"
            f"Sitemap: {site}sitemap.xml\n")


# -------------------------------------------------------------------- png
# Link-preview crawlers (Facebook, LinkedIn, Slack, X, iMessage) mostly
# refuse SVG, so the preview has to be a raster. PNG is the one raster that
# needs nothing but zlib to write.
def png_bytes(width, height, rgb):
    """Encode a width x height RGB byte buffer as a PNG file."""
    stride = width * 3
    if len(rgb) != stride * height:
        raise ValueError("pixel buffer does not match the image size")
    # Each scanline gets filter type 0 (none). Flat colour and long runs are
    # what these images are made of, and deflate handles those on its own.
    raw = b"".join(b"\x00" + bytes(rgb[y * stride:(y + 1) * stride]) for y in range(height))

    def chunk(tag, data):
        return (struct.pack(">I", len(data)) + tag + data
                + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))

    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)   # 8-bit RGB
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr)
            + chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b""))


def png_pixels(data):
    """(IHDR, decompressed scanlines) of a PNG, or None if it is not one.

    Used to decide whether an image changed. Comparing the files byte for byte
    would not do: two zlib builds may compress the same pixels differently, so
    CI would call the committed PNGs stale whenever its zlib is not the one
    they were built with.
    """
    if not data.startswith(b"\x89PNG\r\n\x1a\n"):
        return None
    pos, ihdr, idat = 8, None, b""
    try:
        while pos < len(data):
            n = struct.unpack(">I", data[pos:pos + 4])[0]
            tag, body = data[pos + 4:pos + 8], data[pos + 8:pos + 8 + n]
            if tag == b"IHDR":
                ihdr = body
            elif tag == b"IDAT":
                idat += body
            pos += 12 + n
        return ihdr, zlib.decompress(idat)
    except (struct.error, zlib.error):
        return None


# A 5x7 bitmap font, capitals only. No font library is available without
# pip, and a lowercase set at this size is where hand-drawn glyphs start to
# look home-made; small caps read cleanly at every scale used here. The title
# still has to be in the image: X shows large-image cards with no title text,
# so for it the picture is the whole preview.
_GLYPHS = """
A .###. #...# #...# ##### #...# #...# #...#
B ####. #...# #...# ####. #...# #...# ####.
C .###. #...# #.... #.... #.... #...# .###.
D ####. #...# #...# #...# #...# #...# ####.
E ##### #.... #.... ####. #.... #.... #####
F ##### #.... #.... ####. #.... #.... #....
G .###. #...# #.... #.### #...# #...# .###.
H #...# #...# #...# ##### #...# #...# #...#
I .###. ..#.. ..#.. ..#.. ..#.. ..#.. .###.
J ..### ...#. ...#. ...#. ...#. #..#. .##..
K #...# #..#. #.#.. ##... #.#.. #..#. #...#
L #.... #.... #.... #.... #.... #.... #####
M #...# ##.## #.#.# #.#.# #...# #...# #...#
N #...# #...# ##..# #.#.# #..## #...# #...#
O .###. #...# #...# #...# #...# #...# .###.
P ####. #...# #...# ####. #.... #.... #....
Q .###. #...# #...# #...# #.#.# #..#. .##.#
R ####. #...# #...# ####. #.#.. #..#. #...#
S .#### #.... #.... .###. ....# ....# ####.
T ##### ..#.. ..#.. ..#.. ..#.. ..#.. ..#..
U #...# #...# #...# #...# #...# #...# .###.
V #...# #...# #...# #...# #...# .#.#. ..#..
W #...# #...# #...# #.#.# #.#.# #.#.# .#.#.
X #...# #...# .#.#. ..#.. .#.#. #...# #...#
Y #...# #...# .#.#. ..#.. ..#.. ..#.. ..#..
Z ##### ....# ...#. ..#.. .#... #.... #####
0 .###. #...# #..## #.#.# ##..# #...# .###.
1 ..#.. .##.. ..#.. ..#.. ..#.. ..#.. .###.
2 .###. #...# ....# ...#. ..#.. .#... #####
3 ####. ....# ....# .###. ....# ....# ####.
4 ...#. ..##. .#.#. #..#. ##### ...#. ...#.
5 ##### #.... ####. ....# ....# #...# .###.
6 ..##. .#... #.... ####. #...# #...# .###.
7 ##### ....# ...#. ..#.. .#... .#... .#...
8 .###. #...# #...# .###. #...# #...# .###.
9 .###. #...# #...# .#### ....# ...#. .##..
- ..... ..... ..... .###. ..... ..... .....
/ ....# ....# ...#. ..#.. .#... #.... #....
. ..... ..... ..... ..... ..... .##.. .##..
, ..... ..... ..... ..... .##.. ..#.. .#...
' ..#.. ..#.. .#... ..... ..... ..... .....
" .#.#. .#.#. ..... ..... ..... ..... .....
& .##.. #..#. #.#.. .#... #.#.# #..#. .##.#
( ...#. ..#.. .#... .#... .#... ..#.. ...#.
) .#... ..#.. ...#. ...#. ...#. ..#.. .#...
: ..... .##.. .##.. ..... .##.. .##.. .....
? .###. #...# ....# ...#. ..#.. ..... ..#..
! ..#.. ..#.. ..#.. ..#.. ..#.. ..... ..#..
+ ..... ..#.. ..#.. ##### ..#.. ..#.. .....
= ..... ..... ##### ..... ##### ..... .....
< ...#. ..#.. .#... #.... .#... ..#.. ...#.
> .#... ..#.. ...#. ....# ...#. ..#.. .#...
* ..... ..... .###. .###. .###. ..... .....
"""
FONT = {line[0]: line[2:].split() for line in _GLYPHS.strip().splitlines()}
FONT[" "] = ["....."] * 7

# Characters the titles actually use that the font lacks, mapped to the
# nearest ones it has. Anything else is dropped after NFKD folding, so an
# accent loses its mark rather than turning into a box.
_FOLD = {"—": "-", "–": "-", "−": "-", "·": "*", "•": "*",
         "‘": "'", "’": "'", "“": '"', "”": '"', "×": "X"}


def font_text(s):
    s = "".join(_FOLD.get(c, c) for c in s)
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode()
    return "".join(c for c in s.upper() if c in FONT)


class Canvas:
    """An RGB pixel buffer with just enough drawing for a preview card."""

    def __init__(self, w, h, bg):
        self.w, self.h = w, h
        self.buf = bytearray(bytes(bg) * (w * h))

    def rect(self, x0, y0, x1, y1, rgb):
        x0, x1 = max(0, int(x0)), min(self.w, int(x1))
        y0, y1 = max(0, int(y0)), min(self.h, int(y1))
        if x0 >= x1:
            return
        row = bytes(rgb) * (x1 - x0)
        for y in range(y0, y1):
            i = (y * self.w + x0) * 3
            self.buf[i:i + len(row)] = row

    def dot(self, cx, cy, r, rgb):
        for dy in range(-r, r + 1):
            half = int(math.sqrt(r * r - dy * dy) + 0.5)
            self.rect(cx - half, cy + dy, cx + half + 1, cy + dy + 1, rgb)

    def line(self, pts, rgb, r, dash=0):
        """A polyline r pixels thick; dash > 0 draws dash-pixel dashes."""
        walked = 0.0
        for (x0, y0), (x1, y1) in zip(pts, pts[1:]):
            steps = max(1, int(max(abs(x1 - x0), abs(y1 - y0))))
            seg = math.hypot(x1 - x0, y1 - y0) / steps
            for k in range(steps + 1):
                if not dash or int(walked / dash) % 2 == 0:
                    self.dot(int(x0 + (x1 - x0) * k / steps), int(y0 + (y1 - y0) * k / steps), r, rgb)
                walked += seg if k < steps else 0

    def text(self, x, y, s, scale, rgb):
        for c in s:
            for gy, row in enumerate(FONT[c]):
                for gx, bit in enumerate(row):
                    if bit == "#":
                        self.rect(x + gx * scale, y + gy * scale,
                                  x + (gx + 1) * scale, y + (gy + 1) * scale, rgb)
            x += 6 * scale


def text_width(s, scale):
    return max(0, len(s) * 6 * scale - scale)


def wrap(s, scale, width):
    lines, cur = [], ""
    for word in s.split():
        trial = f"{cur} {word}".strip()
        if cur and text_width(trial, scale) > width:
            lines.append(cur)
            cur = word
        else:
            cur = trial
    return lines + ([cur] if cur else [])


def _hex(c):
    return tuple(int(c[i:i + 2], 16) for i in (1, 3, 5))


def _mix(a, b, t):
    return tuple(round(x + (y - x) * t) for x, y in zip(a, b))


BG, INK, INK_SOFT, REF = _hex("#f7f7f5"), _hex("#1c1b19"), _hex("#5c5a55"), _hex("#9e988c")
ACCENT = _hex("#b4341f")
# The site itself uses one accent everywhere; the previews get a colour per
# subject so a feed of shared links shows at a glance which subject each is.
SUBJECT_COLOURS = {
    "Maths AA HL": _hex("#2458a6"),
    "Physics HL": _hex("#1f7a4d"),
    "Chemistry HL": ACCENT,
}


def _curves(demo, box):
    """[(kind, points)] in pixels for the preview's plot, kind in ref/main/fill.

    Rough shapes of each topic's own animation - the same ones app.js draws on
    the home page cards - so a preview looks like the page it opens.
    """
    x0, y0, x1, y1 = box

    def px(fn, n=240, u0=0.0, u1=1.0):
        out = []
        for i in range(n + 1):
            u = u0 + (u1 - u0) * i / n
            a, b = fn(u)
            out.append((x0 + a * (x1 - x0), y1 - max(0.0, min(1.0, b)) * (y1 - y0)))
        return out

    if demo == "taylor":
        def p5(u):
            x = u * 12 - 6
            return x - x ** 3 / 6 + x ** 5 / 120
        # Stop the polynomial where it leaves the frame - running it flat
        # along the edge would hide the point of the topic, that it diverges.
        inside = [i / 600 for i in range(601) if abs(p5(i / 600)) <= 1.5]
        return [("ref", px(lambda u: (u, 0.5 + 0.32 * math.sin(u * 12 - 6)))),
                ("main", px(lambda u: (u, 0.5 + 0.32 * p5(u)), 240, inside[0], inside[-1]))]
    if demo == "projectile":
        return [("dash", px(lambda u: (u, 3.4 * u * (1 - u)))),
                # Drag: shorter, lower, and it comes down steeper than it went up.
                ("main", px(lambda u: (u * 0.78, 1.8 * u * (1 - u * u))))]
    if demo == "boltzmann":
        def mb(u):
            x = u * 3.2
            return u, 2.2 * x * x * math.exp(-x * x / 1.1)
        return [("fill", px(mb, 120, 0.52, 1.0)), ("main", px(mb))]
    if demo == "orbitals":
        cy, h = (y0 + y1) / 2, (y1 - y0) / 2
        s = [(x0 + 1.1 * h + h * math.cos(a), cy + h * math.sin(a))
             for a in (2 * math.pi * i / 180 for i in range(181))]
        p = []
        for i in range(361):
            a = 2 * math.pi * i / 360
            r = 2.2 * h * abs(math.cos(a)) ** 1.2
            p.append((x0 + 5.2 * h + r * math.cos(a), cy + 0.42 * r * math.sin(a)))
        return [("main", s), ("main", p)]
    # No port yet (or the home page): a damped wave, the collection's motif.
    return [("ref", px(lambda u: (u, 0.5 + 0.4 * math.sin(u * 14)))),
            ("main", px(lambda u: (u, 0.5 + 0.42 * math.exp(-2.2 * u) * math.sin(u * 14))))]


def og_image(title, band_text, demo, colour, w=1200, h=630):
    """A 1200x630 preview: subject band, title, and the topic's curve."""
    pad = 72
    c = Canvas(w, h, BG)
    c.rect(0, 0, w, 96, colour)
    c.text(pad, 34, font_text(band_text), 4, (255, 255, 255))

    # The largest scale at which the title fits in three lines and still
    # leaves the plot most of the lower half; a long title gets smaller type
    # rather than a squashed curve.
    words = font_text(title)
    for scale in (10, 9, 8, 7, 6, 5):
        lines = wrap(words, scale, w - 2 * pad)
        if len(lines) * 10 * scale <= 250 and all(text_width(ln, scale) <= w - 2 * pad
                                                  for ln in lines):
            break
    y = 140
    for ln in lines[:3]:
        c.text(pad, y, ln, scale, INK)
        y += 10 * scale

    box = (pad, max(y + 30, 380), w - pad, 548)
    tint = _mix(BG, colour, 0.28)
    for kind, pts in _curves(demo, box):
        if kind == "fill":
            for (xa, ya), (xb, _) in zip(pts, pts[1:]):
                c.rect(xa, ya, xb + 1, box[3], tint)
        elif kind == "main":
            c.line(pts, colour, 5)
        else:
            c.line(pts, REF, 3, dash=18 if kind == "dash" else 0)
    c.rect(pad, box[3] + 4, w - pad, box[3] + 7, _mix(BG, INK, 0.15))   # axis

    c.rect(pad, 580, pad + 18, 598, colour)
    c.text(pad + 30, 580, font_text(SITE_NAME), 3, INK_SOFT)
    return png_bytes(w, h, c.buf)


# ----------------------------------------------------------------- writing
def write_text(path, text):
    """Write text with LF endings, only if it changed. Returns True if written.

    On a Windows checkout with core.autocrlf the file on disk has CRLF endings
    while the new text has LF; that is not a change, and rewriting it would
    only churn mtimes.
    """
    data = text.encode("utf-8")
    if path.exists() and path.read_bytes().replace(b"\r\n", b"\n") == data:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    return True


def write_png(path, data):
    if path.exists() and png_pixels(path.read_bytes()) == png_pixels(data):
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    return True


def prune(docs, ids):
    """Remove pages and images for topics that no longer exist.

    Only directories whose page carries the GENERATED marker, so nothing
    written by hand under docs/t/ is ever deleted.
    """
    removed = []
    tdir = docs / "t"
    if tdir.is_dir():
        for d in sorted(tdir.iterdir()):
            page = d / "index.html"
            if d.is_dir() and d.name not in ids and page.exists() \
                    and MARKER in page.read_text(encoding="utf-8", errors="replace"):
                shutil.rmtree(d)
                removed.append(d)
    odir = docs / "og"
    if odir.is_dir():
        for f in sorted(odir.glob("*.png")):
            if f.stem not in ids and f.stem != "home":
                f.unlink()
                removed.append(f)
    return removed


def load_topics(root):
    path = root / "topics.json"
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise BuildError(f"no topics.json at {path}")
    except json.JSONDecodeError as e:
        raise BuildError(f"topics.json is not valid JSON: {e}")


def build(root=ROOT, site=None, quiet=False):
    """Validate topics.json under root and regenerate everything in docs/.

    Returns the list of paths that were written or removed.
    """
    root = Path(root)
    site = site_url(site)
    topics = load_topics(root)
    validate(topics, root)

    docs = root / "docs"
    changed = []

    embedded = []
    for t in topics:
        t = dict(t)
        t["source"] = (root / t["folder"] / t["script"]).read_text(encoding="utf-8")
        t["script_url"] = f"{t['folder']}/{t['script']}"
        t["notebook_url"] = f"{REPO}/blob/main/{t['folder']}/{t['notebook']}"
        t["colab_url"] = (
            f"https://colab.research.google.com/github/iyu210-tech/"
            f"Capstone_Repository/blob/main/{t['folder']}/{t['notebook']}"
        )
        embedded.append(t)
    payload = json.dumps(embedded, indent=2, ensure_ascii=False)
    js = f"// {MARKER} by hand.\nwindow.TOPICS = {payload};\n"
    if write_text(docs / "topics.js", js):
        changed.append(docs / "topics.js")

    index = docs / "index.html"
    if not index.exists():
        raise BuildError(f"no template at {index}")
    template = home_page(index.read_text(encoding="utf-8").replace("\r\n", "\n"), site)
    if write_text(index, template):
        changed.append(index)

    for t in topics:
        page = docs / "t" / t["id"] / "index.html"
        if write_text(page, topic_page(template, t, site)):
            changed.append(page)
        colour = SUBJECT_COLOURS.get(t["subject"], ACCENT)
        img = og_image(t["title"], f"{t['subject']} · {t['syllabus']}", t.get("demo"), colour)
        if write_png(docs / "og" / f"{t['id']}.png", img):
            changed.append(docs / "og" / f"{t['id']}.png")

    home_img = og_image("Hard IB topics you can run", "IB Higher Level * Maths * Physics * Chemistry",
                        None, ACCENT)
    if write_png(docs / "og" / "home.png", home_img):
        changed.append(docs / "og" / "home.png")

    if write_text(docs / "sitemap.xml", sitemap(topics, site)):
        changed.append(docs / "sitemap.xml")
    if write_text(docs / "robots.txt", robots(site)):
        changed.append(docs / "robots.txt")

    changed += prune(docs, {t["id"] for t in topics})

    if not quiet:
        print(f"built {len(topics)} topics for {site}")
        for p in changed:
            print(f"  wrote {p.relative_to(root).as_posix()}" if p.exists()
                  else f"  removed {p.relative_to(root).as_posix()}")
        if not changed:
            print("  everything already up to date")
    return changed


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--root", type=Path, default=ROOT,
                    help="repository to build (default: the one this file is in)")
    args = ap.parse_args(argv)
    try:
        build(args.root)
    except BuildError as e:
        # A plain message and a non-zero exit, not a traceback: this is what a
        # Vercel or Render build log shows, and it should say what to fix.
        print(f"build_site.py: {e}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
